#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v37D2/character"
require "ddex/ern/v37D2/current_territory_code"
require "ddex/ern/v37D2/detailed_resource_contributor"
require "ddex/ern/v37D2/title"

module DDEX module ERN module V37D2  # :nodoc: all

class CollectionDetailsByTerritory < Element
  include ROXML


  xml_name "CollectionDetailsByTerritory"

      xml_accessor :excluded_territory_codes, :as => [DDEX::ERN::V37D2::CurrentTerritoryCode], :from => "ExcludedTerritoryCode", :required => false
      xml_accessor :territory_codes, :as => [DDEX::ERN::V37D2::CurrentTerritoryCode], :from => "TerritoryCode", :required => false
      xml_accessor :titles, :as => [DDEX::ERN::V37D2::Title], :from => "Title", :required => false
      xml_accessor :contributors, :as => [DDEX::ERN::V37D2::DetailedResourceContributor], :from => "Contributor", :required => false
      xml_accessor :complete?, :from => "IsComplete", :required => false
      xml_accessor :characters, :as => [DDEX::ERN::V37D2::Character], :from => "Character", :required => false


  

end

end end end
