#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v37D2/c_line"
require "ddex/ern/v37D2/character"
require "ddex/ern/v37D2/collection_collection_reference_list"
require "ddex/ern/v37D2/collection_details_by_territory"
require "ddex/ern/v37D2/collection_id"
require "ddex/ern/v37D2/collection_resource_reference_list"
require "ddex/ern/v37D2/collection_type"
require "ddex/ern/v37D2/collection_work_reference_list"
require "ddex/ern/v37D2/detailed_resource_contributor"
require "ddex/ern/v37D2/event_date"
require "ddex/ern/v37D2/p_line"
require "ddex/ern/v37D2/title"

module DDEX module ERN module V37D2  # :nodoc: all

class Collection < Element
  include ROXML


  xml_name "Collection"

      xml_accessor :collection_ids, :as => [DDEX::ERN::V37D2::CollectionId], :from => "CollectionId", :required => true
      xml_accessor :collection_types, :as => [DDEX::ERN::V37D2::CollectionType], :from => "CollectionType", :required => false
      xml_accessor :collection_reference, :from => "CollectionReference", :required => true
      xml_accessor :equivalent_release_reference, :from => "EquivalentReleaseReference", :required => false
      xml_accessor :titles, :as => [DDEX::ERN::V37D2::Title], :from => "Title", :required => false
      xml_accessor :sequence_number, :as => Integer, :from => "SequenceNumber", :required => false
      xml_accessor :contributors, :as => [DDEX::ERN::V37D2::DetailedResourceContributor], :from => "Contributor", :required => false
      xml_accessor :characters, :as => [DDEX::ERN::V37D2::Character], :from => "Character", :required => false
      xml_accessor :collection_collection_reference_list, :as => DDEX::ERN::V37D2::CollectionCollectionReferenceList, :from => "CollectionCollectionReferenceList", :required => false
      xml_accessor :complete?, :from => "IsComplete", :required => false
      xml_accessor :duration, :from => "Duration", :required => false
      xml_accessor :duration_of_musical_content, :from => "DurationOfMusicalContent", :required => false
      xml_accessor :creation_date, :as => DDEX::ERN::V37D2::EventDate, :from => "CreationDate", :required => false
      xml_accessor :release_date, :as => DDEX::ERN::V37D2::EventDate, :from => "ReleaseDate", :required => false
      xml_accessor :original_release_date, :as => DDEX::ERN::V37D2::EventDate, :from => "OriginalReleaseDate", :required => false
      xml_accessor :original_language, :from => "OriginalLanguage", :required => false
      xml_accessor :collection_details_by_territories, :as => [DDEX::ERN::V37D2::CollectionDetailsByTerritory], :from => "CollectionDetailsByTerritory", :required => false
      xml_accessor :collection_resource_reference_list, :as => DDEX::ERN::V37D2::CollectionResourceReferenceList, :from => "CollectionResourceReferenceList", :required => false
      xml_accessor :collection_work_reference_list, :as => DDEX::ERN::V37D2::CollectionWorkReferenceList, :from => "CollectionWorkReferenceList", :required => false
      xml_accessor :representative_image_reference, :from => "RepresentativeImageReference", :required => false
      xml_accessor :p_lines, :as => [DDEX::ERN::V37D2::PLine], :from => "PLine", :required => false
      xml_accessor :c_lines, :as => [DDEX::ERN::V37D2::CLine], :from => "CLine", :required => false


  
      xml_accessor :language_and_script_code, :from => "@LanguageAndScriptCode", :required => false
    
  

end

end end end
