#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v37D2/description"

module DDEX module ERN module V37D2  # :nodoc: all

class Genre < Element
  include ROXML


  xml_name "Genre"

      xml_accessor :genre_text, :as => DDEX::ERN::V37D2::Description, :from => "GenreText", :required => true
      xml_accessor :sub_genre, :as => DDEX::ERN::V37D2::Description, :from => "SubGenre", :required => false


  
      xml_accessor :language_and_script_code, :from => "@LanguageAndScriptCode", :required => false
    
  

end

end end end
