#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v37D2/event_date"
require "ddex/ern/v37D2/image_details_by_territory"
require "ddex/ern/v37D2/image_type"
require "ddex/ern/v37D2/resource_proprietary_id"
require "ddex/ern/v37D2/title"

module DDEX module ERN module V37D2  # :nodoc: all

class Image < Element
  include ROXML


  xml_name "Image"

      xml_accessor :image_type, :as => DDEX::ERN::V37D2::ImageType, :from => "ImageType", :required => false
      xml_accessor :artist_related?, :from => "IsArtistRelated", :required => false
      xml_accessor :image_ids, :as => [DDEX::ERN::V37D2::ResourceProprietaryId], :from => "ImageId", :required => true
      xml_accessor :resource_reference, :from => "ResourceReference", :required => true
      xml_accessor :titles, :as => [DDEX::ERN::V37D2::Title], :from => "Title", :required => false
      xml_accessor :creation_date, :as => DDEX::ERN::V37D2::EventDate, :from => "CreationDate", :required => false
      xml_accessor :image_details_by_territories, :as => [DDEX::ERN::V37D2::ImageDetailsByTerritory], :from => "ImageDetailsByTerritory", :required => true


  
      xml_accessor :updated?, :from => "@IsUpdated", :required => false
    
  
      xml_accessor :language_and_script_code, :from => "@LanguageAndScriptCode", :required => false
    
  

end

end end end
