#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v37D2/messaging_party"

module DDEX module ERN module V37D2  # :nodoc: all

class MessageAuditTrailEvent < Element
  include ROXML


  xml_name "MessageAuditTrailEvent"

      xml_accessor :messaging_party_descriptor, :as => DDEX::ERN::V37D2::MessagingParty, :from => "MessagingPartyDescriptor", :required => true
      xml_accessor :date_time, :as => DateTime, :from => "DateTime", :required => true


  

end

end end end
