#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v37D2/message_audit_trail_event"

module DDEX module ERN module V37D2  # :nodoc: all

class MessageAuditTrail < Element
  include ROXML


  xml_name "MessageAuditTrail"

      xml_accessor :message_audit_trail_events, :as => [DDEX::ERN::V37D2::MessageAuditTrailEvent], :from => "MessageAuditTrailEvent", :required => true


  
      xml_accessor :language_and_script_code, :from => "@LanguageAndScriptCode", :required => false
    
  

end

end end end
