#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v37D2/description"
require "ddex/ern/v37D2/release_id"

module DDEX module ERN module V37D2  # :nodoc: all

class Deal < Element; include ROXML end

class RelatedReleaseOfferSet < Element
  include ROXML


  xml_name "RelatedReleaseOfferSet"

      xml_accessor :release_description, :as => DDEX::ERN::V37D2::Description, :from => "ReleaseDescription", :required => false

      
      xml_accessor :release_ids, :as => [DDEX::ERN::V37D2::ReleaseId], :from => "ReleaseId", :required => false

      
      xml_accessor :deals, :as => [DDEX::ERN::V37D2::Deal], :from => "Deal", :required => false



  
      xml_accessor :language_and_script_code, :from => "@LanguageAndScriptCode", :required => false
    
  

end

end end end
