#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v37D2/release_resource_reference"

module DDEX module ERN module V37D2  # :nodoc: all

class ReleaseResourceReferenceList < Element
  include ROXML


  xml_name "ReleaseResourceReferenceList"

      xml_accessor :release_resource_references, :as => [DDEX::ERN::V37D2::ReleaseResourceReference], :from => "ReleaseResourceReference", :required => true


  

end

end end end
