#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v37D2/carrier_type"
require "ddex/ern/v37D2/distribution_channel_type"
require "ddex/ern/v37D2/technical_instantiation"
require "ddex/ern/v37D2/use_type"
require "ddex/ern/v37D2/user_interface_type"

module DDEX module ERN module V37D2  # :nodoc: all

class Usage < Element
  include ROXML


  xml_name "Usage"

      xml_accessor :use_types, :as => [DDEX::ERN::V37D2::UseType], :from => "UseType", :required => true
      xml_accessor :user_interface_types, :as => [DDEX::ERN::V37D2::UserInterfaceType], :from => "UserInterfaceType", :required => false
      xml_accessor :distribution_channel_types, :as => [DDEX::ERN::V37D2::DistributionChannelType], :from => "DistributionChannelType", :required => false
      xml_accessor :carrier_types, :as => [DDEX::ERN::V37D2::CarrierType], :from => "CarrierType", :required => false
      xml_accessor :technical_instantiation, :as => DDEX::ERN::V37D2::TechnicalInstantiation, :from => "TechnicalInstantiation", :required => false
      xml_accessor :number_of_usages, :as => Integer, :from => "NumberOfUsages", :required => false


  

end

end end end
