#
# Do not edit. Automatically generated by `rake generate:main`.
#
module DDEX
  module ERN
    module V37D2
      extend DDEX
      require_standard("ern", "3.7D2") # Is this the correct way to reference the version?
    end
  end
end